# A3 Bonus Task 1: LLM-based Method

Reference:
- [Bertopic](https://maartengr.github.io/BERTopic/index.html)
- [Fastopic](https://github.com/BobXWu/FASTopic)

In [ ]:
!pip install bertopic
!pip install bertopic[visualization]
# !pip install "bertopic[visualization]" # In case you are using zsh shell which uses square brackets for pattern matching

Requirement already satisfied: bertopic[visualization] in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (0.16.4)
WARNING: bertopic 0.16.4 does not provide the extra 'visualization'
Requirement already satisfied: hdbscan>=0.8.29 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from bertopic[visualization]) (0.8.40)
Requirement already satisfied: numpy>=1.20.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from bertopic[visualization]) (1.26.4)
Requirement already satisfied: pandas>=1.1.5 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from bertopic[visualization]) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from bertopic[visualization]) (5.24.1)
Requirement already satisfied: scikit-learn>=0.22.2.post1 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from bertopic[visualization]) (1.5.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from bertopic[visualization]) (3.3.1)
Requirement already satisfied: tqdm>=4.41.1 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from bertopic[visualization]) (4.67.1)
Requirement already satisfied: umap-learn>=0.5.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from bertopic[visualization]) (0.5.7)
Requirement already satisfied: scipy>=1.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from hdbscan>=0.8.29->bertopic[visualization]) (1.13.1)
Requirement already satisfied: joblib>=1.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from hdbscan>=0.8.29->bertopic[visualization]) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from pandas>=1.1.5->bertopic[visualization]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from pandas>=1.1.5->bertopic[visualization]) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from pandas>=1.1.5->bertopic[visualization]) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from plotly>=4.7.0->bertopic[visualization]) (9.0.0)
Requirement already satisfied: packaging in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from plotly>=4.7.0->bertopic[visualization]) (24.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from scikit-learn>=0.22.2.post1->bertopic[visualization]) (3.5.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from sentence-transformers>=0.4.1->bertopic[visualization]) (4.46.3)
Requirement already satisfied: torch>=1.11.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from sentence-transformers>=0.4.1->bertopic[visualization]) (2.5.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from sentence-transformers>=0.4.1->bertopic[visualization]) (0.26.3)
Requirement already satisfied: Pillow in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from sentence-transformers>=0.4.1->bertopic[visualization]) (10.4.0)
Requirement already satisfied: numba>=0.51.2 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from umap-learn>=0.5.0->bertopic[visualization]) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from umap-learn>=0.5.0->bertopic[visualization]) (0.5.13)
Requirement already satisfied: filelock in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic[visualization]) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic[visualization]) (2024.10.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic[visualization]) (6.0.2)
Requirement already satisfied: requests in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic[visualization]) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic[visualization]) (4.11.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from numba>=0.51.2->umap-learn>=0.5.0->bertopic[visualization]) (0.43.0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic[visualization]) (1.16.0)
Requirement already satisfied: networkx in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic[visualization]) (3.4.2)
Requirement already satisfied: jinja2 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic[visualization]) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic[visualization]) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic[visualization]) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic[visualization]) (2024.11.6)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic[visualization]) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic[visualization]) (0.4.5)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic[visualization]) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic[visualization]) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic[visualization]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic[visualization]) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/miniconda3/envs/apml/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic[visualization]) (2024.8.30)

## Model Training

In [1]:
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

model = BERTopic(language="english", calculate_probabilities=True, nr_topics="auto", embedding_model="all-MiniLM-L6-v2")

In [2]:
topics, probs = model.fit_transform(docs)

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [3]:
model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,6391,-1_the_to_of_and,"[the, to, of, and, is, in, that, it, you, for]",[\nA question for you - can you give me the na...
1,0,9963,0_the_to_of_and,"[the, to, of, and, that, is, in, it, for, you]","[\nNo smiley on the part about atheism, I see...."
2,1,1840,1_the_he_game_in,"[the, he, game, in, to, and, team, was, of, that]",[\nI agree that Keenan is an excellent choice....
3,2,86,2_water_the_of_to,"[water, the, of, to, in, and, mwra, is, dept, ...",[FURY OF MOTHER NATURE\n\nMan's contribution t...
4,3,45,3_paint_wax_plastic_it,"[paint, wax, plastic, it, car, and, the, scrat...",[since at least one other person was intereste...
5,4,44,4_mouse_driver_the_it,"[mouse, driver, the, it, problem, mice, is, an...","[Can't guarantee that it'll work for everyone,..."
6,5,39,5_oil_the_it_drain,"[oil, the, it, drain, car, my, change, on, to,...",[Does anyone know how to reset the service ind...
7,6,38,6_battery_batteries_concrete_acid,"[battery, batteries, concrete, acid, discharge...",[[heats of formation deleted]\n\nThe major pro...
8,7,37,7_clutch_transmission_shift_gear,"[clutch, transmission, shift, gear, car, shift...",[In rec.autos you write:\n\n\nThis McLaren aut...
9,8,35,8_kirlian_photography_leaf_pictures,"[kirlian, photography, leaf, pictures, krillea...",[=|> \n=|> >I think that's the correct spellin...
10,9,34,9_fan_cpu_heat_sink,"[fan, cpu, heat, sink, fans, the, on, chip, it...",[\n<speaking of CPU fans>\n\n\nDo these CPU Fa...
11,10,27,10_ax_max_g9v_b8f,"[ax, max, g9v, b8f, a86, pl, 145, 1d9, 34u, 0t]",[\n\n------------ Part 13 of 14 ------------\n...
12,11,23,11_odometer_sensor_car_the,"[odometer, sensor, car, the, mileage, speedo, ...",[\nI have owned my Sprint from the beginning a...
13,12,20,12_eye_prk_cornea_is,"[eye, prk, cornea, is, vision, rk, the, bates,...",[I am quite near sighted.\n\nI've recently rec...
14,13,20,13_cancer_center_medical_research,"[cancer, center, medical, research, centers, o...","[:When I was a school boy, my biology teacher ..."
15,14,19,14_water_cooling_steam_towers,"[water, cooling, steam, towers, plants, nuclea...","[\n Actually, fossil fuel plants run hot..."
16,15,19,15_envelope_lines_solar_airplane,"[envelope, lines, solar, airplane, flight, the...",[\n----------\n\nThis is not news. In fact it...
17,16,18,16_den_p3_p2_p1,"[den, p3, p2, p1, radius, sphere, points, p13,...",[\n\n\nIt's not a bad question: I don't have a...
18,17,17,17_chemistry_book_paperback_guide,"[chemistry, book, paperback, guide, spice, wri...",[SOMEONE PLEASE BUY THESE BOOKS!!!!! I AM NOT...
19,18,16,18_kidney_stones_calcium_b6,"[kidney, stones, calcium, b6, magnesium, vitam...","[has no\nmitigate\nliterature,\n\nFirst, let m..."
20,19,16,19_piece_jacket_clothing_pants,"[piece, jacket, clothing, pants, women, pocket...","[\nWomen's pants rarely have pockets and most,..."
21,20,15,20_wasps_my_centipedes_chiggers,"[wasps, my, centipedes, chiggers, to, and, on,...","[\nI'll probably get flamed for this, but when..."
22,21,15,21_fonts_font_the_gary,"[fonts, font, the, gary, and, select, cleeve, ...","[\nIT'S BACK!!!!!!\n\nCongratulations, you've ..."
23,22,14,22_ground_grounding_conductor_neutral,"[ground, grounding, conductor, neutral, wire, ...","[\nNot according to the NEC nor the CEC, as ex..."
24,23,12,23_boards_solder_mask_green,"[boards, solder, mask, green, board, cw, ssb, ...",[The color of the board shows the composition ...
25,24,12,24_skin_hearing_ear_greasy,"[skin, hearing, ear, greasy, acne, aids, dry, ...","[Claude, I've not heard or read anything that ..."
26,25,11,25_voltage_generator_output_current,"[voltage, generator, output, current, the, ohm...","[Hi,\n\n I've just built a valve preamp and ..."
27,26,10,26_moscow_aviation_russian_su,"[moscow, aviation, russian, su, institute, kal...","[\nCorrection, and some more info: The Kalinin..."
28,27,10,27_meat_smoke_carcinogenic_carcinogens,"[meat, smoke, carcinogenic, carcinogens, wood,...",[\nSome recent postings remind me that I had r...

In [4]:
model.get_topic(0)

[('the', 0.028207780199548654),
 ('to', 0.0233422985475853),
 ('of', 0.022987379069115917),
 ('and', 0.02175386806089543),
 ('that', 0.01907680729459392),
 ('is', 0.018794780651832058),
 ('in', 0.01878424225271633),
 ('it', 0.017032595257858472),
 ('for', 0.01535407900528289),
 ('you', 0.015015213497355366)]

In [5]:
model.get_document_info(docs)

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document
0,\n\nI am sure some bashers of Pens fans are pr...,1,1_the_he_game_in,"[the, he, game, in, to, and, team, was, of, that]",[\nI agree that Keenan is an excellent choice....,the - he - game - in - to - and - team - was -...,0.705405,False
1,My brother is in the market for a high-perform...,-1,-1_the_to_of_and,"[the, to, of, and, is, in, that, it, you, for]",[\nA question for you - can you give me the na...,the - to - of - and - is - in - that - it - yo...,0.413201,False
2,\n\n\n\n\tFinally you said what you dream abou...,-1,-1_the_to_of_and,"[the, to, of, and, is, in, that, it, you, for]",[\nA question for you - can you give me the na...,the - to - of - and - is - in - that - it - yo...,0.668885,False
3,\nThink!\n\nIt's the SCSI card doing the DMA t...,0,0_the_to_of_and,"[the, to, of, and, that, is, in, it, for, you]","[\nNo smiley on the part about atheism, I see....",the - to - of - and - that - is - in - it - fo...,0.927472,False
4,1) I have an old Jasmine drive which I cann...,0,0_the_to_of_and,"[the, to, of, and, that, is, in, it, for, you]","[\nNo smiley on the part about atheism, I see....",the - to - of - and - that - is - in - it - fo...,0.820299,False
...,...,...,...,...,...,...,...,...
18841,DN> From: nyeda@cnsvax.uwec.edu (David Nye)\nD...,0,0_the_to_of_and,"[the, to, of, and, that, is, in, it, for, you]","[\nNo smiley on the part about atheism, I see....",the - to - of - and - that - is - in - it - fo...,0.805587,False
18842,\nNot in isolated ground recepticles (usually ...,22,22_ground_grounding_conductor_neutral,"[ground, grounding, conductor, neutral, wire, ...","[\nNot according to the NEC nor the CEC, as ex...",ground - grounding - conductor - neutral - wir...,0.521752,False
18843,I just installed a DX2-66 CPU in a clone mothe...,9,9_fan_cpu_heat_sink,"[fan, cpu, heat, sink, fans, the, on, chip, it...",[\n<speaking of CPU fans>\n\n\nDo these CPU Fa...,fan - cpu - heat - sink - fans - the - on - ch...,1.000000,False
18844,\nWouldn't this require a hyper-sphere. In 3-...,16,16_den_p3_p2_p1,"[den, p3, p2, p1, radius, sphere, points, p13,...",[\n\n\nIt's not a bad question: I don't have a...,den - p3 - p2 - p1 - radius - sphere - points ...,1.000000,False
18845,After a tip from Gary Crum (crum@fcom.cc.utah....,0,0_the_to_of_and,"[the, to, of, and, that, is, in, it, for, you]","[\nNo smiley on the part about atheism, I see....",the - to - of - and - that - is - in - it - fo...,1.000000,False

NB:
- There is a list of different [**word embedding models**](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html) for you to choose from.
- If you are interested in hyperparameter tuning, you can take a look at [this](https://maartengr.github.io/BERTopic/getting_started/parameter%20tuning/parametertuning.html).

## Visualizations

In [10]:
model.visualize_topics()

In [17]:
model.visualize_distribution(probs[0])

In [7]:
model.visualize_barchart()

In [9]:
model.visualize_heatmap()

More to explore:
- [In-depth usage of visualization methods](https://maartengr.github.io/BERTopic/getting_started/visualization/visualize_topics.html)

## Question: data preprocessing?

### Example: stop words

Stop words can sometimes appear in topic representations, but they are generally undesirable as they add little interpretive value. However, removing stop words during preprocessing is not recommended because transformer-based embedding models rely on the full context for accurate embeddings.

A better approach is to use `CountVectorizer` to preprocess documents after generating embeddings and clustering them.

In [3]:
model.get_topic_info()[1:11]

,Topic,Count,Name,Representation,Representative_Docs
1,0,1800,0_game_team_he_games,"[game, team, he, games, season, hockey, year, ...","[The problem with your nihilistic approach, Ro..."
2,1,895,1_key_encryption_clipper_chip,"[key, encryption, clipper, chip, keys, be, to,...",[\nI am not an expert in the cryptography scie...
3,2,796,2_scsi_drive_card_drives,"[scsi, drive, card, drives, disk, ide, control...",[wlsmith@valve.heart.rri.uwo.ca (Wayne Smith) ...
4,3,532,3_idjits_hello_ites_cheek,"[idjits, hello, ites, cheek, dancing, hi, yep,...","[Lets not forget , Hello,, \nDancing With Idji..."
5,4,376,4_car_bike_engine_miles,"[car, bike, engine, miles, cars, dealer, rear,...","[\n\n\n\nYou know, I'm a Ford fan, I must say,..."
6,5,335,5_space_launch_nasa_earth,"[space, launch, nasa, earth, venus, mission, s...",[COMMERCIAL SPACE NEWS/SPACE TECHNOLOGY INVEST...
7,6,320,6_batf_fbi_koresh_fire,"[batf, fbi, koresh, fire, they, compound, was,...",[This was posted by Lyn Bates to the firearms-...
8,7,317,7_dos_window_windows_os,"[dos, window, windows, os, xfree86, server, wi...",[I am working on an X-Window based application...
9,8,311,8_god_is_jehovah_that,"[god, is, jehovah, that, atheists, atheism, of...","[\nNo smiley on the part about atheism, I see...."
10,9,308,9_health_insurance_candida_patients,"[health, insurance, candida, patients, medical...","[\nWhen you buy insurance where you live, it i..."

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer_model = CountVectorizer(stop_words="english")
model.update_topics(docs, vectorizer_model=vectorizer_model)

In [5]:
model.get_topic_info()[1:11]

,Topic,Count,Name,Representation,Representative_Docs
1,0,1800,0_game_team_games_season,"[game, team, games, season, hockey, players, p...","[The problem with your nihilistic approach, Ro..."
2,1,895,1_key_encryption_clipper_chip,"[key, encryption, clipper, chip, keys, escrow,...",[\nI am not an expert in the cryptography scie...
3,2,796,2_scsi_drive_card_drives,"[scsi, drive, card, drives, ide, disk, control...",[wlsmith@valve.heart.rri.uwo.ca (Wayne Smith) ...
4,3,532,3_idjits_hello_ites_cheek,"[idjits, hello, ites, cheek, dancing, hi, yep,...","[Lets not forget , Hello,, \nDancing With Idji..."
5,4,376,4_car_bike_engine_miles,"[car, bike, engine, miles, cars, dealer, musta...","[\n\n\n\nYou know, I'm a Ford fan, I must say,..."
6,5,335,5_space_launch_nasa_venus,"[space, launch, nasa, venus, earth, mission, s...",[COMMERCIAL SPACE NEWS/SPACE TECHNOLOGY INVEST...
7,6,320,6_batf_fbi_koresh_compound,"[batf, fbi, koresh, compound, agents, gas, war...",[This was posted by Lyn Bates to the firearms-...
8,7,317,7_dos_window_windows_os,"[dos, window, windows, os, xfree86, server, mi...",[I am working on an X-Window based application...
9,8,311,8_god_jehovah_atheists_atheism,"[god, jehovah, atheists, atheism, religion, el...","[\nNo smiley on the part about atheism, I see...."
10,9,308,9_health_insurance_candida_patients,"[health, insurance, candida, patients, medical...","[\nWhen you buy insurance where you live, it i..."

Take-away:
- Removing stop words is more critical in traditional bag-of-words models or static word embeddings (e.g., Word2Vec, GloVe) to reduce dimensionality and noise.
- However, when using transformer-based models (e.g., BERT, GPT, RoBERTa) to obtain word embeddings, removing stop words is generally not necessary. 
- Transformer models generate contextualized embeddings, meaning each word’s representation depends on the surrounding context. Even stop words like “the,” “is,” or “in” are assigned meaningful embeddings based on their role in the sentence.
- Removing stop words can disrupt the context and alter the embeddings of the remaining words. Removing stop words before feeding text to a transformer might leave “gaps” in the sequence, altering the sentence structure and context representation.

Think about:
- URLs
- numbers
- lowercasing
- sentence spliting
- ...